package com.aim.questionnaire.dao.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class QuestionnaireEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_info.question_name
     *
     * @mbg.generated
     */
    private String questionName;

    private String projectName;

    private String emailTitle;

    private String emailContent;

    public String getEmailTitle() {
        return emailTitle;
    }

    public void setEmailTitle(String emailTitle) {
        this.emailTitle = emailTitle;
    }

    public String getEmailContent() {
        return emailContent;
    }

    public void setEmailContent(String emailContent) {
        this.emailContent = emailContent;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    private String questionEndContent;

    public String getQuestionEndContent() {
        return questionEndContent;
    }

    public void setQuestionEndContent(String questionEndContent) {
        this.questionEndContent = questionEndContent;
    }

    private String projectId;

    public String getProjectId() {
        return projectId;
    }

    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_info.question_content
     *
     * @mbg.generated
     */
    private String questionContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_info.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_info.creation_date
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_info.last_updated_by
     *
     * @mbg.generated
     */
    private String lastUpdatedBy;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_info.last_update_date
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    private String dataId;

    private Integer status;

    /**
     * 删除
     */
    public static final int DELETE = 0;
    /**
     * 暂停
     */
    public static final int STOP = 1;
    /**
     * 发布运行
     */
    public static final int RUN = 2;
    /**
     * 结束
     */
    public static final int END = 3;
    private Date releaseTime;

    private Date startTime;
    private Date endTime;

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public Date getReleaseTime() {
        return releaseTime;
    }

    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getDataId() {
        return dataId;
    }

    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getQuestionName() {
        return questionName;
    }

    public void setQuestionName(String questionName) {
        this.questionName = questionName;
    }

    public String getQuestionContent() {
        return questionContent;
    }

    public void setQuestionContent(String questionContent) {
        this.questionContent = questionContent;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @Override
    public String toString() {
        return "QuestionnaireEntity{" +
                "id='" + id + '\'' +
                ", questionName='" + questionName + '\'' +
                ", questionContent='" + questionContent + '\'' +
                ", createdBy='" + createdBy + '\'' +
                ", creationDate=" + creationDate +
                ", lastUpdatedBy='" + lastUpdatedBy + '\'' +
                ", lastUpdateDate=" + lastUpdateDate +
                ", dataId='" + dataId + '\'' +
                '}';
    }
}